### ISSUE TITLE
Add a screenshot of the running application to the README

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/ru102js#18]
Update `README.md` to add a screenshot of the running application, showing the map view with the solar site markers on it.  For this you will need to follow the instructions in the README to get the application running.

This is part of our participation in Hacktoberfest 2021.  Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us?  Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by LuizHAP** [comment]
can u please assign to me? :D

**Comment by SuzeShardlow** [comment]
Sure thing @LuizHAP!  Please work on this issue and open your pull request within two calendar days.  Thanks and have fun :)

**Comment by LuizHAP** [comment]
@SuzeShardlow How can I generate the solar sitemap on my map? I have Redis on my computer, but it doesn't show up as information.

![image](https://user-images.githubusercontent.com/20971507/136633679-e27b94ee-6444-47fc-86fa-65afa89c2991.png)
![image](https://user-images.githubusercontent.com/20971507/136633693-dee38919-a48d-4430-b33a-7dcf043ecdca.png)

**Comment by simonprickett** [comment]
Also congrats for getting the application up and running locally!
