### ISSUE TITLE
Add the option to use Redis via Docker Compose for this course.

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/ru102js#20]
Add a `docker-compose.yml` file that uses the RedisTimeSeries Docker container (https://hub.docker.com/r/redislabs/redistimeseries), and configure Redis in that container to persist data to a local folder named "redisdata".  Here's an example file from another project that works like this (this one uses the redismod container but it's the same idea): https://github.com/redislabs-training/node-js-crash-course/blob/main/docker-compose.yml

This is part of our participation in Hacktoberfest 2021. Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by rajat9garg** [comment]
hey @simonprickett I would like to take this issue.
